platform :ios, ‘8.0’
target 'SemitrailerUsedCar' do
source 'https://github.com/CocoaPods/Specs.git'
pod 'AFNetworking', '3.1.0'
pod 'YYModel','1.0.4'
pod 'YMNetWork', '0.0.3'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'YYWebImage'
end
